name: periodic_healthcheck
on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  ping:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://fs-cicd-pokedex.fly.dev/health